name: Docker Image CI
on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
jobs:
 build:
   strategy:
     matrix:
       runs-on: [ubuntu-latest, self-hosted]
   runs-on: ${{ matrix.runs-on }}
   steps:
   - uses: actions/checkout@v4
   
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
   
   - name: Build and push Docker image
     run: |
       IMAGE_TAG=$(date +%s)
       docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$IMAGE_TAG-${{ matrix.runs-on }}
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$IMAGE_TAG-${{ matrix.runs-on }}
