name: Docker Image CI
on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]
jobs:
 build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v4
   
   - name: Install Docker
     run: |
       # Remove any existing Docker packages
       sudo apt-get remove -y docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc || true
       
       # Update package index
       sudo apt-get update
       
       # Install required dependencies
       sudo apt-get install -y \
           apt-transport-https \
           ca-certificates \
           curl \
           software-properties-common
       
       # Add Docker's official GPG key
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
       
       # Add Docker repository
       sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
       
       # Update package index again
       sudo apt-get update
       
       # Install Docker CE
       sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        # Enable User Acess
       sudo usermod -aG docker $USER

        # Enable User
       newgrp docker
       
       # Verify Docker installation
       docker --version
   
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
   
   - name: Build and push Docker image
     run: |
       IMAGE_TAG=$(date +%s)
       docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$IMAGE_TAG
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:$IMAGE_TAG
