name: Ubuntu EC2 Server Update & Java Install

on:
 push:
   branches: [ "main" ]
 workflow_dispatch:

jobs:
 prepare-server:
   strategy:
     matrix:
       runs-on: [ubuntu-latest, self-hosted, macos-latest]
   runs-on: ${{ matrix.runs-on }}
   steps:
     - uses: actions/checkout@v4

     - name: Update and Upgrade Server
       run: |
         sudo apt-get update
         sudo apt-get upgrade -y

     - name: Install Java 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '17'

     - name: Verify Java Installation
       run: |
         java --version
         javac --version

     
         
